# Generated by Django 2.1.5 on 2019-01-18 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogback', '0003_auto_20190117_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
